# Generated by Django 3.2.16 on 2023-01-05 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Conference')),
                ('nombre', models.TextField(unique=True, verbose_name='Conferencia')),
                ('img', models.URLField(null=True, verbose_name='URL imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Division')),
                ('nombre', models.TextField(unique=True, verbose_name='División')),
                ('conferencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.conferencia')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre de la franquicia')),
                ('lugar', models.TextField(verbose_name='Localización')),
                ('playoffs', models.PositiveSmallIntegerField(default=0, verbose_name='Participaciones en Playoffs')),
                ('campeonatos', models.PositiveSmallIntegerField(default=0, verbose_name='Campeonatos NBA')),
                ('titulos_conferencia', models.PositiveSmallIntegerField(default=0, verbose_name='Títulos de conferencia')),
                ('titulos_division', models.PositiveSmallIntegerField(default=0, verbose_name='Títulos de división')),
                ('escudo', models.URLField(null=True, verbose_name='URL de su escudo')),
                ('estadio', models.TextField(verbose_name='Nombre de la cancha')),
                ('url', models.URLField(null=True, verbose_name='URL en nba.com')),
                ('wins', models.PositiveSmallIntegerField(default=0, verbose_name='Victorias esta temporada')),
                ('loses', models.PositiveSmallIntegerField(default=0, verbose_name='Derrotas esta temporada')),
                ('conferencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.conferencia')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.division')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
                ('dorsal', models.PositiveSmallIntegerField(null=True, verbose_name='Dorsal')),
                ('edad', models.PositiveSmallIntegerField(null=True, verbose_name='Edad')),
                ('altura', models.CharField(max_length=30, null=True, verbose_name='Altura (m)')),
                ('peso', models.TextField(null=True, verbose_name='Peso (kg)')),
                ('exp', models.PositiveSmallIntegerField(null=True, verbose_name='Años como profesional')),
                ('imagen', models.URLField(null=True, verbose_name='URL de su fotografía')),
                ('draft', models.TextField(null=True, verbose_name='Draft')),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.equipo')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre en inglés')),
                ('nombre', models.TextField(verbose_name='Nombre en español')),
                ('iso3', models.CharField(max_length=3, verbose_name='Abreviatura de 3 siglas')),
                ('bandera', models.URLField(verbose_name='URL de su bandera')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Posición (inglés)')),
                ('nombre', models.TextField(verbose_name='Posición (español)')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='SeasonLeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(verbose_name='Category')),
                ('categoria', models.TextField(verbose_name='Categoría')),
                ('stat', models.FloatField()),
                ('lider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.jugador')),
            ],
        ),
        migrations.AddField(
            model_name='jugador',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pais'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='posicion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.posicion'),
        ),
    ]
